### ISSUE TITLE
pypi release ?

### ISSUE THREAD

**Issue by weber-s** [pydiscourse/pydiscourse#83]
Hello there!

I just needed the `latest_posts` endpoint, and it seem's that it is in the 1.4.0 tag, but this release is not yet published in pypi. Could you please release it? :)

Thanks a lot for this package!

**Comment by bennylope** [comment]
No. 😔

But! 🙌

Have a version 1.5.0 instead: https://pypi.org/project/pydiscourse/1.5.0/
